# fly.toml app configuration file generated for dry-dawn-3102 on 2023-09-06T11:08:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-dawn-3102"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
